### ISSUE TITLE
unexpected number of optimization variables in Ipopt 

### ISSUE THREAD

**Issue by orsoromeo** [ethz-adrl/towr#20]
I cannot figure out why the number of variables that I pass to IPOPT in the NLP formulation is not the same number that is printed out by IPOPT itself just before solving the problem. These two numbers should match in my opinion. I initially thought it was a bug of my formulation but I see that this happens also for the hopper example. I just want to understand if this is an expected event or not and in case it is then what is the number that is being printed by IPOPT?

For example if you sum up the number of variables defined by TOWR in this test the sum will be 204:
![var_number](https://user-images.githubusercontent.com/14978496/42353033-a0a0d9ba-8083-11e8-9e59-a345df556067.png)

But if you look at what IPOPT is saying then you see that the variables number is 165:
![vars](https://user-images.githubusercontent.com/14978496/42353112-14bf6fb4-8084-11e8-84f6-1cbfd490e9d4.png)

So what is the difference between these two numbers?

**Comment by awinkler** [comment]
Yes, good observation. This difference comes  since `IPOPT` doesn't regard variables with same upper and lower bound as variables anymore, but just fixes their value. 

In `towr` the motion-splines are parameterized by nodes, but then various nodes in this spline are fixed in advanced, such as initial pos/vel/footholts, final, etc. Other elements that are fixed are those coming from the phase-based endeffector parameterization, and also don't show up in `IPOPT` anymore, e.g. 
https://github.com/ethz-adrl/towr/blob/44c92450be6acd6b08470e6e2764f915c9946e8f/towr/src/phase_nodes.cc#L246

Of course we could also remove the variables from the optimization problem instead of setting equal upper and lower bound. However, using bounds and always adding the full spline as variables we found makes code/formulation more extensible and elegant.

**Comment by orsoromeo** [comment]
Great. I did not expect Ipopt's preprocessing to be so "clever". I agree that it makes perfectly sense to keep the fixed variables for a more elegant formulation of the problem. Especially considered that Ipopt takes care of that and therefore the computation time should not be affected.
