### ISSUE TITLE
PhaseNodes initialization towards goal

### ISSUE THREAD

**Issue by orsoromeo** [ethz-adrl/towr#28]
I am playing with TOWR and making some unit test to understand how it works.

In this test:[towr/test/phase_nodes_test.cc](https://github.com/orsoromeo/towr/blob/master/towr/test/phase_nodes_test.cc) I am trying to test how the values of the phase nodes change.

There are four main unit tests. These tests check the first 3 values of the motion/force phaseNode and make sure they correspond to the desired initial end effector position/force:
1. [PASS] PhaseNodesTest [motionPhaseNodesStartInSwing](https://github.com/orsoromeo/towr/blob/ab6cb55a03a68120dde8cfdcbc69f74eb7ea1cee/towr/test/phase_nodes_test.cc#L25)

2. [FAIL] PhaseNodesTest [motionPhaseNodesStartInStance](https://github.com/orsoromeo/towr/blob/ab6cb55a03a68120dde8cfdcbc69f74eb7ea1cee/towr/test/phase_nodes_test.cc#L63)

3. [FAIL] PhaseNodesTest [forcePhaseNodesStartInSwing](https://github.com/orsoromeo/towr/blob/ab6cb55a03a68120dde8cfdcbc69f74eb7ea1cee/towr/test/phase_nodes_test.cc#L140)

4. [PASS] PhaseNodesTest [forcePhaseNodesStartInStance](https://github.com/orsoromeo/towr/blob/ab6cb55a03a68120dde8cfdcbc69f74eb7ea1cee/towr/test/phase_nodes_test.cc#L101)

I would like to understand why tests 2 and 3 are failing. I guess this has something to do with the fact that they failing phaseNodes are set to be constant in the initial phase, but I don't see if this is a bug or an expected behavior.

If you're interested in running the tests should be aligned with version 1.3.2. So the phase_node_test.cc should compile just fine when you compile the TOWR library with enabled testing (if you installed gtest). you can run the tests by ./towr-test inside towr/towr/build.

**Comment by orsoromeo** [comment]
Ok I think I got what is going on.

The Nodes [GetValue()](https://github.com/ethz-adrl/towr/blob/8b41f6c7de2355c64c4b2744571c297c94ce888c/towr/src/nodes.cc#L112) function loops over all the optimization nodes and over all the node components of the optimization node (i guess finding two different names for optimization and components node could help) and only the value of the last node component is saved.  

So for example let's consider a 1 dimensional problem with 3 phases (stance->swing->stance) where I want to spline my values from 0 to 1. The *optimization nodes* will be 3 but the number of *nodes components* is different (let's say 5 in case of polynomials_in_changing_phase = 2).

so splined values will be: 
` [0, 0.25], {0.5}, [0.75, 1] `
where [ ] means stance and { } means swing phase

So when I call the GetValue() I was expecting to get following values: 
` {0, 0.25, 0.5, 0.75, 1}` 
but what is the values that are actually returned are the last of each optimization node meaning: 
`{0.25, 0.5, 1}`

I am still not sure of why the GetValue() is done like this though.

**Comment by awinkler** [comment]
Hi, this is a good question.

Yes, the [Nodes::GetValues()](https://github.com/ethz-adrl/towr/blob/3faca80d1d1a2bf4324ce3da5838738b4e1b9190/towr/src/nodes.cc#L105) function (overriding the general function of [ifopt::Component::GetValues()](https://github.com/ethz-adrl/ifopt/blob/7fae1fc58887cd6ee7b427a9250b99fa0b07938b/ifopt_core/include/ifopt/composite.h#L99))
returns *only* the optimization variables. As you noticed, sometimes multiple nodes values are filled  by the *same* optimization variable (e.g. in the image below position of the nodes to the left and right of `p_{i,1}` are given by *one* optimization variable). 

![phase_nodes2](https://user-images.githubusercontent.com/4179579/42951297-29e84c6a-8b76-11e8-80ef-8dd9f6c8b5de.png)

So for you example above:
If GetValues() returned these variables:  
`{0.25, 0.5, 1}`, 
the values of the 5 nodes in the spline would actually be  
`{[0.25, 0.25], {0.5}, [1, 1]}`,  
There is no information lost. Since we know how the splines are parameterized (e.g. 2 polynomials in changing phase), one can fully reconstruct the entire spline with these 3 values. 

I'm polishing the wording in the phase_nodes a bit and will see how I can make this a bit more intuitve to understand, thanks!

**Comment by orsoromeo** [comment]
Thanks for the explaination @awinkler !

Don't you risk in this way to have a small error between the initial value of the spline and the one that you actually wanted? So if I want to spline from 0 to 1, I would expect to see something like:
`{[0.0, 0.0], {0.5}, [1, 1]}`
rather than:
So if I want to spline a foot position from 0 to 1 the actual

**Comment by awinkler** [comment]
The initial position or force is enforced exactly, since there is only **one optimization variable** responsible for this, and can be directly constrained. If I want the initial foot position to start at **x=0.25m** exactly, and the foot starts in a stance phase,  we can put a constraint (or bound) on that optimization variable. Since the foot cannot move during this first stance phase, this defines the first two node values as:  
{[**0.25**, **0.25**], {0.5}, [1, 1]}  

The same analogy holds for a force spline, just that constant and non-constant phases are switched. Does that answer your question?

**Comment by orsoromeo** [comment]
Sorry for being slow here but I still don't understand how I set my initial desired foothold in practice. In the first example the initial desired value is 0.0  (set using the initializeTowardsGoal function) the first value that is returned by the GetValues function is actually 0.25 (a new value that I did not expect).

In your example in the same way if I set the first value to be 0.25 and then I call the GetValues I will actually get ([0.43, 0.43] {0.62} [1 1]}

This is done regardless of any constraint/boundary on that variable.

**Comment by awinkler** [comment]
Ah, this is a different topic in a way. The `InitializeTowardsGoal()` function is just a handy helper function to set initial values, and just knows about a sequence of nodes (not even about phase-nodes). All it does is set linear interpolated positions for all nodes. 
https://github.com/ethz-adrl/towr/blob/03a089dff2fa86878d395d96b872ba9d953e7e92/towr/src/nodes.cc#L172

This is just the initialization, you can also use different starting values by going through the nodes on your own and set different positions. This **initialization can violate all constraints/boundaries**, but after the solver iterations the solution will fulfill what we talked about above.

**Comment by orsoromeo** [comment]
Great thanks for the clarification!
