### ISSUE TITLE
Issues regarding force penalization

### ISSUE THREAD

**Issue by psguo** [ethz-adrl/towr#49]
Hi, Alex! If we add the end effector force penalization function called PenalizeEndeffectorForces() to the objective function, the final output will be an unreasonable walking gait (Hyq) which contains some very large forces acting on the ground. Do you have any insight on that? Also, it seems the function MakeForcesCost() add the variable from EEForceNodes at derivative (kPos) & dimension (Z). Could you help to clarify this more? Why we need to use kPos derivative to get the force rather than kVel or kAcc?

**Comment by awinkler** [comment]
Hi! I haven't played to much around with the first question, perhaps a cost that minimizes changes in forces, instead of actual force values is better?

For the second question, the enum "kPos" is named a bit suboptmal, yes. It's ued in this case as the zero-derivative (actual value of the forces), wheras kVel would refer to the first derivative (change in forces, slope of force profile).
